backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "people"
    label: "People"
    folder: "content"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { name: "showonlyimage", widget: "hidden", default: false }
      - { name: "draft", widget: "hidden", default: false }
      - { name: "date", widget: "hidden", default: "2020" }
      - {
          label: "Weight (1-3), smaller goes to top",
          name: "weight",
          widget: "number",
          default: 2,
          min: 1,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - { name: "date", widget: "hidden", default: "2020" }
          - { name: "title", widget: "hidden", default: "More About Us" }
          - name: "_build"
            widget: "hidden"
            fields:
              - { name: "list", widget: "hidden", default: false }
              - { name: "render", widget: "hidden", default: true }
